<a href="https://colab.research.google.com/github/nitinlodhi019/Machine-Learning/blob/main/Data-Analysis/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ndArray**

In [ ]:
import numpy as np

In [ ]:
# single dimensional nd array
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#2 dimensional ndarray
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(arr1.ndim)
type(arr1)

2


numpy.ndarray

In [ ]:
# usingnp.zeros,np.ones,empty,random
arr2=np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr3=np.ones((3,2))
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
# create identity matrix
arr4=np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# generate a array in a given range
arr5=np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# in a range
arr6=np.arange(5,20,2)
arr6

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# take 3 parameter and give equal distance
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
# numpy version
print(np.__version__)


1.25.2


# properties and attribute


In [ ]:
arr


array([1, 2, 3, 4, 5])

In [ ]:
# give array size
arr.shape

(5,)

In [ ]:
arr2.shape

(2, 3)

In [ ]:
# 2D array
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[1,0]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [1, 0]]])

In [ ]:
arr9.shape

(3, 2, 2)

In [ ]:
arr9.ndim

3

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# give number of item in ndarray
arr1.size

9

In [ ]:
arr1.itemsize

8

In [ ]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr8.itemsize

8

In [ ]:
arr8.dtype

dtype('float64')

In [ ]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]],

       [[9., 0.],
        [1., 0.]]])

# Lists Vs Arrays

In [ ]:
lista=range(100)
arr11=np.arange(100)

In [ ]:
import sys

In [ ]:
# get one item from the list and multiply by total item in list
print(sys.getsizeof(80)*len(lista))

2800


In [ ]:
print(arr11.itemsize*arr11.size)

800


In [ ]:
import time

In [ ]:
x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()
c=[(x+y) for x,y in zip(x,y)]
print(time.time()-start_time)

1.377676010131836


In [ ]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start_time=time.time()
c=a+b
print(time.time()-start_time)

0.06408119201660156


# Indexing,Slicing and Iteration


In [ ]:
arr12=np.arange(24)
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[3]

4

In [ ]:
arr[2:4]

array([3, 4])

In [ ]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# 3rd element on 2nd row
arr12[1,2]

6

In [ ]:
arr12[2]

array([ 8,  9, 10, 11])

In [ ]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr12[:,1]

array([ 1,  5,  9, 13, 17, 21])

In [ ]:
# find 2 coloumn
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [ ]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [ ]:
arr12[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [ ]:
for i in arr:
  print(i)

1
2
3
4
5


In [ ]:
for i in arr12:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [ ]:
for i in np.nditer(arr12):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# operations

In [ ]:
import numpy as np

In [ ]:
arr13=np.array([1,2,3,4,5])
arr14=np.array([1,4,6,2,9])

In [ ]:
arr13-arr14

array([ 0, -2, -3,  2, -4])

In [ ]:
arr13*arr14

array([ 1,  8, 18,  8, 45])

In [ ]:
arr13*2

array([ 2,  4,  6,  8, 10])

In [ ]:
arr14>4

array([False, False,  True, False,  True])

In [ ]:
arr15=np.arange(6).reshape(2,3)
arr16=np.arange(6,12).reshape(3,2)

In [ ]:
print(arr15)

[[0 1 2]
 [3 4 5]]


In [ ]:
arr16

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr15.dot(arr16)

array([[ 28,  31],
       [100, 112]])

In [ ]:
arr15.max()

5

In [ ]:
arr16.min()

6

In [ ]:
arr16

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr16.min(axis=0)

array([6, 7])

In [ ]:
arr16.max(axis=1)

array([ 7,  9, 11])

In [ ]:
arr16.sum()

51

In [ ]:
arr16.sum(axis=1)

array([13, 17, 21])

8.5