<a href="https://colab.research.google.com/github/nitinlodhi019/Machine-Learning/blob/main/Multiple-Linear-Regression/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


In [ ]:
X, y = make_regression(n_samples = 100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [ ]:
data = pd.DataFrame({'x1':X[:,0], 'x2':X[:,1], 'target':y})

In [ ]:
data.head()

x1        x2     target
0  0.444215  1.216942  77.345992
1  0.616155 -0.639495 -62.507587
2  0.856679  0.786268  -8.869597
3  0.760411  0.151272 -62.668656
4 -0.489851  0.667685  68.579574

In [ ]:
data.shape

(100, 3)

In [ ]:
fig = px.scatter_3d(data, x='x1', y='x2', z='target')
fig.show()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

# Normalize your data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize the model
model = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None)

# Fit the model to the normalized data
model.fit(X_train_scaled, y_train)

# Make predictions on the normalized test data
predictions = model.predict(X_test_scaled)


In [ ]:
print("MAE", mean_absolute_error(y_test, predictions))
print("MSE", mean_squared_error(y_test, predictions))
print("R2 score", r2_score(y_test, predictions))

MAE 34.32706835580117
MSE 1668.6978005869478
R2 score 0.41301272017129353


In [ ]:
model.coef_

array([ 0.53053315, 38.85689685])

In [ ]:
model.intercept_

-10.541705163673994

In [ ]:
import numpy as np

# Let's assume you want to create a grid of feature values for prediction
x = np.linspace(0, 1, 10)
y = np.linspace(0, 1, 10)
xGrid, yGrid = np.meshgrid(x, y)

# Stack xGrid and yGrid into a single 2D array for prediction
final = np.c_[xGrid.ravel(), yGrid.ravel()]

# Make predictions
z_final = model.predict(final).reshape(10, 10)

# Now you can use z_final as needed
z = z_final


In [ ]:
fig = px.scatter_3d(data, x='x1', y='x2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()


#new

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
